name: Build Linux Container

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'Dockerfile.no-x11'
      - 'resources/InterBase_2020_Linux/**'
      - '.github/workflows/build-linux-container.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'Dockerfile.no-x11'
      - 'resources/InterBase_2020_Linux/**'
      - '.github/workflows/build-linux-container.yml'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Build and push Linux Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/interbase-linux:latest
          ${{ secrets.DOCKER_USERNAME }}/interbase-linux:${{ github.sha }}
        
    - name: Build and push Linux No-X11 Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.no-x11
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/interbase-linux-nox11:latest
          ${{ secrets.DOCKER_USERNAME }}/interbase-linux-nox11:${{ github.sha }}