name: Build Windows Container

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile.windows'
      - 'resources/InterBase_2020_Windows/**'
      - '.github/workflows/build-windows-container.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'Dockerfile.windows'
      - 'resources/InterBase_2020_Windows/**'
      - '.github/workflows/build-windows-container.yml'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Build Windows Docker image
      run: |
        docker build -f Dockerfile.windows -t interbase-win2k25 .
        
    - name: Tag and push to Docker Hub
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      run: |
        docker tag interbase-win2k25 ${{ secrets.DOCKER_USERNAME }}/interbase-win2k25:latest
        docker tag interbase-win2k25 ${{ secrets.DOCKER_USERNAME }}/interbase-win2k25:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/interbase-win2k25:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/interbase-win2k25:${{ github.sha }}
        
    - name: Save image as artifact
      run: |
        docker save interbase-win2k25 -o interbase-windows.tar
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: interbase-windows-image
        path: interbase-windows.tar
        retention-days: 7